### ISSUE TITLE
After a network interruption event handler doesn't show an update anymore

### ISSUE THREAD

**Issue by Soberia** [LonamiWebs/Telethon#1330]
After a network interruption (Like turn WiFi on/off) no more update prints on the console.
The log file shows that just before the interruption, all updates had been received successfully

**Checklist**
* [True] I have searched for this issue before posting it and there isn't a duplicate.
* [True] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```
import asyncio, logging
from telethon import TelegramClient, events

logging.basicConfig(format='[%(levelname) 5s/%(asctime)s] %(name)s: %(message)s',
                    filename='log',
                    level=logging.DEBUG)


@events.register(events.NewMessage())
async def handler(event):
    print(event.message.stringify())


async def main():
    async with TelegramClient(...) as client:
        client.add_event_handler(handler)
        await client.run_until_disconnected()


asyncio.run(main())
```

<details><summary><strong>Log</strong></summary>

```
[DEBUG/2019-11-15 14:19:01,228] asyncio: Using proactor: IocpProactor
[ INFO/2019-11-15 14:19:01,257] telethon.network.mtprotosender: Connecting to 149.154.167.92:443/TcpFull...
[DEBUG/2019-11-15 14:19:01,257] telethon.network.mtprotosender: Connection attempt 1...
[DEBUG/2019-11-15 14:19:01,411] telethon.network.mtprotosender: Connection success!
[DEBUG/2019-11-15 14:19:01,412] telethon.network.mtprotosender: Starting send loop
[DEBUG/2019-11-15 14:19:01,412] telethon.network.mtprotosender: Starting receive loop
[ INFO/2019-11-15 14:19:01,412] telethon.network.mtprotosender: Connection to 149.154.167.92:443/TcpFull complete!
[DEBUG/2019-11-15 14:19:01,803] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:01,803] telethon.extensions.messagepacker: Assigned msg_id = 6759483704763631004 to InvokeWithLayerRequest (1b8c574fc10)
[DEBUG/2019-11-15 14:19:01,859] telethon.network.mtprotosender: Encrypting 1 message(s) in 72 bytes for sending
[DEBUG/2019-11-15 14:19:01,861] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:01,861] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:01,861] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:02,014] telethon.network.mtprotosender: Handling bad salt for message 6759483704763631004
[DEBUG/2019-11-15 14:19:02,015] telethon.network.mtprotosender: 1 message(s) will be resent
[DEBUG/2019-11-15 14:19:02,015] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:02,015] telethon.extensions.messagepacker: Assigned msg_id = 6759483705906580708 to InvokeWithLayerRequest (1b8c574fc10)
[DEBUG/2019-11-15 14:19:02,015] telethon.network.mtprotosender: Encrypting 1 message(s) in 72 bytes for sending
[DEBUG/2019-11-15 14:19:02,017] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:02,017] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:02,017] telethon.extensions.messagepacker: Assigned msg_id = 6759483705914580128 to MsgsAck (1b8c574fd30)
[DEBUG/2019-11-15 14:19:02,017] telethon.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[DEBUG/2019-11-15 14:19:02,018] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:02,018] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:02,174] telethon.network.mtprotosender: Handling container
[DEBUG/2019-11-15 14:19:02,174] telethon.network.mtprotosender: Handling new session created
[DEBUG/2019-11-15 14:19:02,174] telethon.network.mtprotosender: Handling acknowledge for [6759483705906580708]
[DEBUG/2019-11-15 14:19:02,175] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:02,179] telethon.network.mtprotosender: Handling RPC result for message 6759483705906580708
[DEBUG/2019-11-15 14:19:02,180] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:02,180] telethon.extensions.messagepacker: Assigned msg_id = 6759483706566579600 to GetStateRequest (1b8c574ffd0)
[DEBUG/2019-11-15 14:19:02,180] telethon.network.mtprotosender: Encrypting 1 message(s) in 20 bytes for sending
[DEBUG/2019-11-15 14:19:02,181] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:02,181] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:02,181] telethon.extensions.messagepacker: Assigned msg_id = 6759483706570582172 to MsgsAck (1b8c574fb20)
[DEBUG/2019-11-15 14:19:02,181] telethon.network.mtprotosender: Encrypting 1 message(s) in 60 bytes for sending
[DEBUG/2019-11-15 14:19:02,183] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:02,183] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:02,356] telethon.network.mtprotosender: Handling RPC result for message 6759483706566579600
[DEBUG/2019-11-15 14:19:02,356] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:02,357] telethon.extensions.messagepacker: Assigned msg_id = 6759483707274763844 to GetStateRequest (1b8c574ffd0)
[DEBUG/2019-11-15 14:19:02,357] telethon.network.mtprotosender: Encrypting 1 message(s) in 20 bytes for sending
[DEBUG/2019-11-15 14:19:02,358] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:02,358] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:02,358] telethon.extensions.messagepacker: Assigned msg_id = 6759483707278761648 to MsgsAck (1b8c574fc10)
[DEBUG/2019-11-15 14:19:02,358] telethon.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[DEBUG/2019-11-15 14:19:02,359] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:02,359] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:02,531] telethon.network.mtprotosender: Handling RPC result for message 6759483707274763844
[DEBUG/2019-11-15 14:19:02,531] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:06,114] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2019-11-15 14:19:06,114] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:06,114] telethon.extensions.messagepacker: Assigned msg_id = 6759483723484515460 to GetUsersRequest (1b8c57683d0)
[DEBUG/2019-11-15 14:19:06,114] telethon.network.mtprotosender: Encrypting 1 message(s) in 32 bytes for sending
[DEBUG/2019-11-15 14:19:06,115] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:06,115] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:06,116] telethon.extensions.messagepacker: Assigned msg_id = 6759483723492515832 to MsgsAck (1b8c57685b0)
[DEBUG/2019-11-15 14:19:06,116] telethon.network.mtprotosender: Encrypting 1 message(s) in 44 bytes for sending
[DEBUG/2019-11-15 14:19:06,117] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:06,117] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:06,285] telethon.network.mtprotosender: Handling RPC result for message 6759483723484515460
[DEBUG/2019-11-15 14:19:06,285] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:08,914] telethon.network.mtprotosender: Handling update Updates
[DEBUG/2019-11-15 14:19:08,915] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:09,115] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2019-11-15 14:19:09,115] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:11,977] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2019-11-15 14:19:11,978] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:12,703] telethon.network.mtprotosender: Handling update Updates
[DEBUG/2019-11-15 14:19:12,704] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:12,959] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2019-11-15 14:19:12,960] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:21,932] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2019-11-15 14:19:21,933] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:22,823] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2019-11-15 14:19:22,823] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:24,673] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2019-11-15 14:19:24,674] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:26,438] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2019-11-15 14:19:26,438] telethon.network.mtprotosender: Receiving items from the network...
[ INFO/2019-11-15 14:19:33,632] telethon.network.connection.connection: The server closed the connection
[WARNING/2019-11-15 14:19:33,632] telethon.network.connection.connection: Unhandled <class 'FileNotFoundError'> on disconnect: [WinError 53] The network path was not found
[ INFO/2019-11-15 14:19:33,633] telethon.network.mtprotosender: Connection closed while receiving data
[DEBUG/2019-11-15 14:19:33,633] telethon.network.mtprotosender: Closing current connection...
[WARNING/2019-11-15 14:19:33,633] telethon.network.connection.connection: Unhandled <class 'FileNotFoundError'> on disconnect: [WinError 53] The network path was not found
[ INFO/2019-11-15 14:19:33,633] telethon.network.mtprotosender: Connecting to 149.154.167.92:443/TcpFull...
[DEBUG/2019-11-15 14:19:33,634] telethon.network.mtprotosender: Connection attempt 1...
[WARNING/2019-11-15 14:19:33,635] telethon.network.mtprotosender: Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[DEBUG/2019-11-15 14:19:34,646] telethon.network.mtprotosender: Connection attempt 2...
[WARNING/2019-11-15 14:19:40,179] telethon.network.mtprotosender: Attempt 2 at connecting failed: FileNotFoundError: [WinError 53] The network path was not found
[DEBUG/2019-11-15 14:19:41,184] telethon.network.mtprotosender: Connection attempt 3...
[DEBUG/2019-11-15 14:19:41,628] telethon.network.mtprotosender: Connection success!
[DEBUG/2019-11-15 14:19:41,628] telethon.network.mtprotosender: Starting send loop
[DEBUG/2019-11-15 14:19:41,628] telethon.network.mtprotosender: Starting receive loop
[ INFO/2019-11-15 14:19:41,628] telethon.network.mtprotosender: Connection to 149.154.167.92:443/TcpFull complete!
[DEBUG/2019-11-15 14:19:41,628] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:41,629] telethon.extensions.messagepacker: Assigned msg_id = 6759483875866429556 to MsgsAck (1b8c5768bb0)
[DEBUG/2019-11-15 14:19:41,629] telethon.network.mtprotosender: Encrypting 1 message(s) in 108 bytes for sending
[DEBUG/2019-11-15 14:19:41,630] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:19:41,630] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:19:41,631] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:19:41,787] telethon.network.mtprotosender: Handling new session created
[DEBUG/2019-11-15 14:19:41,788] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:20:02,326] telethon.extensions.messagepacker: Assigned msg_id = 6759483964851845184 to PingRequest (1b8c574fca0)
[DEBUG/2019-11-15 14:20:02,326] telethon.network.mtprotosender: Encrypting 1 message(s) in 28 bytes for sending
[DEBUG/2019-11-15 14:20:02,327] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:20:02,327] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:20:02,327] telethon.extensions.messagepacker: Assigned msg_id = 6759483964855883040 to MsgsAck (1b8c574f4c0)
[DEBUG/2019-11-15 14:20:02,328] telethon.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[DEBUG/2019-11-15 14:20:02,329] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:20:02,329] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:20:02,492] telethon.network.mtprotosender: Handling pong for message 6759483964851845184
[DEBUG/2019-11-15 14:20:02,492] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:21:02,338] telethon.extensions.messagepacker: Assigned msg_id = 6759484222595519120 to PingRequest (1b8c574ff10)
[DEBUG/2019-11-15 14:21:02,338] telethon.network.mtprotosender: Encrypting 1 message(s) in 28 bytes for sending
[DEBUG/2019-11-15 14:21:02,340] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:21:02,340] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:21:02,340] telethon.extensions.messagepacker: Assigned msg_id = 6759484222603513772 to MsgsAck (1b8c574fc40)
[DEBUG/2019-11-15 14:21:02,340] telethon.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[DEBUG/2019-11-15 14:21:02,341] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:21:02,341] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:21:02,497] telethon.network.mtprotosender: Handling pong for message 6759484222595519120
[DEBUG/2019-11-15 14:21:02,497] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2019-11-15 14:22:02,354] telethon.extensions.messagepacker: Assigned msg_id = 6759484480356432628 to PingRequest (1b8c574fbe0)
[DEBUG/2019-11-15 14:22:02,354] telethon.network.mtprotosender: Encrypting 1 message(s) in 28 bytes for sending
[DEBUG/2019-11-15 14:22:02,355] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:22:02,356] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:22:02,356] telethon.extensions.messagepacker: Assigned msg_id = 6759484480364511204 to MsgsAck (1b8c574fca0)
[DEBUG/2019-11-15 14:22:02,356] telethon.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[DEBUG/2019-11-15 14:22:02,357] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2019-11-15 14:22:02,357] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2019-11-15 14:22:02,508] telethon.network.mtprotosender: Handling pong for message 6759484480356432628
[DEBUG/2019-11-15 14:22:02,508] telethon.network.mtprotosender: Receiving items from the network...
```

</details>

**Comment by jobbok** [comment]
After experiencing the same issue as above, I've been able to 'fix' it by commenting out the call to self._state.reset() in the method_reconnect in network/mtprotosender.py. Not sure whether this is a proper fix or whether it may create new issues but in my case (which is quite similar to above) it seems to work fine now.
 
```
# Start with a clean state (and thus session ID) to avoid old msgs
# self._state.reset()
```

**Comment by Soberia** [comment]
> ```
> # self._state.reset()
> ```

Yes, this is working but I don't know about consequences.
For now I prefer to use ping to know when internet is down and reconnect the client manually until @Lonami confirm this

**Comment by BlackBeard98** [comment]
I am getting the same issue I hope @Lonami help us all  as soon as he/she can

**Comment by Soberia** [comment]
It seems this problem has been fixed in version 1.13
So I close this issue

**Comment by Lonami** [comment]
I don't recall any recent change regarding updates, so it wouldn't surprise me if it's just Telegram acting different. Because other people claimed they had this issue, I'd rather keep this open.

**Comment by sinarezaei** [comment]
I'm facing the same issue
Commenting out `self._state.reset()` or `self._start_reconnect(e)` after 'Connection closed while receiving data' log did not fix it.
