### ISSUE TITLE
Client disconecting

### ISSUE THREAD

**Issue by ticoti** [LonamiWebs/Telethon#198]
I have the client permanently on receiving updates, and it disconnects and doesnt reconnect so it does not catch updates once it is disconected.

I have tried restarting the script every 10 minutes, but even that way, some times disconnects and dont get the updates.

I have something like this:

client = TelegramClient('dir', api_id, api_hash)
client.connect()
client.add_update_handler(receive)
while 1:
        time.sleep(2)

**Comment by Lonami** [comment]
Are you sure it disconnects, or is it connected but it doesn't receive updates? Because those are ifferent issues.

**Comment by ticoti** [comment]
I wouldnt know to say,

I have the log active, and it doesnt log anything else when it is not working, I dont know if it is because it has stopped getting updates of it is has disconnected

**Comment by roman-dowakin** [comment]
@Lonami Hi! I think it's like in https://github.com/LonamiWebs/Telethon/issues/178
I had similar situation, so I added `state = client.invoke(tl.functions.updates.GetStateRequest())` in a loop and get `ConnectionError` in an hour, and `.reconnect` didn't help (`ConnectionResetError: [Errno 54] Connection reset by peer`)

So right now, I'm testing this code:
```
while True:
    print(".", end='')
    sys.stdout.flush()
    sleep(10)
    try:
        state = tg.invoke(tl.functions.updates.GetStateRequest())
    except (TimeoutError, ConnectionError):
        print('TimeoutError, try reconnecting')
        tg.connect()
        tg.add_update_handler(update_handler)
    print(",", end='')
    sys.stdout.flush()
```

**Comment by ticoti** [comment]
This is the last log message always that there is a disconection or whatever happens 
2017-08-17 14:55:59,573 - telethon.telegram_bare_client - DEBUG - Updates thread released the lock

**Comment by imdoneok** [comment]
I'm facing the almost this problem
the program works just fine and suddenly it disconnects
this is what happens in a while loop running `client.connect()`
`True
True
True
True
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/usr/Telethon/telethon/telegram_client.py", line 146, in connect
    return super().connect()
  File "/home/usr/Telethon/telethon/telegram_bare_client.py", line 134, in connect
    self._sender.connect()
  File "/home/usr/Telethon/telethon/network/mtproto_sender.py", line 36, in connect
    self.transport.connect()
  File "/home/usr/Telethon/telethon/network/tcp_transport.py", line 22, in connect
    timeout=round(self.timeout.seconds))
  File "/home/usr/Telethon/telethon/extensions/tcp_client.py", line 40, in connect
    self._socket.connect((ip, port))
socket.timeout: timed out
`
and here's traceback in my code
`Traceback (most recent call last):
  File "code.py", line 23, in <module>
    if not client.is_user_authorized():
  File "/home/usr/Telethon/telethon/telegram_client.py", line 254, in is_user_authorized
    return self.session and self.get_me() is not None
  File "/home/usr/Telethon/telethon/telegram_client.py", line 348, in get_me
    return self(GetUsersRequest([InputUserSelf()]))[0]
  File "/home/usr/Telethon/telethon/telegram_client.py", line 205, in invoke
    request, updates=updates
  File "/home/usr/Telethon/telethon/telegram_bare_client.py", line 331, in invoke
    raise ValueError('You must be connected to invoke requests!')
ValueError: You must be connected to invoke requests!
`
and so far the only way i could fix this was end session from my phone and get a new login code and same thing happens after a few sec!

**Comment by amir3code** [comment]
I had the same issue, I realized that these are network errors and sometimes are Flood Errors.
If you intentionally or accidentally flood the system you get disconnected and have to be connected again.
I managed this situation with a self calling try/except code.
Hope this helps.

**Comment by Lonami** [comment]
> flood the system you get disconnected

Yeah that's intended behavior, I mean, the flood may be as long as several minutes so why stay connected the whole time? Not sure how to handle that more gracefully.

**Comment by robsske** [comment]
I have the same, how about a if connected function?

**Comment by Lonami** [comment]
You mean like `client.sender.is_connected()` @robsske?

**Comment by Lonami** [comment]
A few things have changed. Please try out the version on the `master` branch and report feedback.

**Comment by Lonami** [comment]
Yet more things have changed as of `v0.13.5`. I'll assume this has been fixed. If it has not, leave a comment or something and we can reopen the issue.

**Comment by aminimani** [comment]
Problem still exists.
After some time the script wont  receive updates.
I wonder whether it gets disconnected or it just stops receiving updates.
I have enabled logging and there is no message in log file too.

**Comment by Lonami** [comment]
`DEBUG` logging should definitely show something. However, it is true that if the client is very passive Telegram will eventually stop sending updates. You can easily force them with a loop that makes requests every few minutes though.

**Comment by aminimani** [comment]
actually the client is active. Even running a script that sends a message every 5 minutes and then deletes it didn't help.
