### ISSUE TITLE
FloodWaitError

### ISSUE THREAD

**Issue by mehrant95** [LonamiWebs/Telethon#990]
I recently face FloodWaitError exactly the same way as in issue #494. Reading the answers i found that i should use `get_input_entity()` instead of `get_entity()`. I found that `get_input_entity()` tries searching inside the session sqlite database to see if a match is found and if no match found, it then tries to send a resolve username request to Telegram. Inside the session database, table entities, there are columns title and username but i couldn't find any method to retrieve title and username from local database using `get_input_entity()`. Is there any method ?

**Comment by Lonami** [comment]
No, there are no methods to get title/username from the local database. You could do it yourself if you really want, or use your own cache.

**Comment by mehrant95** [comment]
To be sure, does `get_input_entity()` method request telegram whenever there is no match in local database? Then if it sends request to telegram server, does it fetch username and title or it just fetches id and hash?

**Comment by Lonami** [comment]
You can actually see that by yourself:
https://github.com/LonamiWebs/Telethon/blob/080585da498675e523deb759abf6c8e2f5a59578/telethon/client/users.py#L226-L310

**Comment by mehrant95** [comment]
Oh, i totally forgot about documentation. It says "Invite links make an API call **always** and are expensive" but i tried `get_input_entity()` with a `http://t.me/joinchat/AAAA...` link **off-line** and it returned the result correctly, what's going wrong?
Making API calls means that it fetches all chat info like username and title ? or it just requests minimal information?

**Comment by Lonami** [comment]
What's wrong is the documentation, and should be fixed (thanks for pointing it out).https://github.com/LonamiWebs/Telethon/commit/2ca8ddbfb41b7b28eea2692cd6e22779e502ae01 addresses that change.

**Comment by mehrant95** [comment]
Thanks for you answers.
For the last question, i still don't know where to start. You said "do it yourself or use your own cache". 
For your first solution, is there any telethon API for retrieving data from local database or i should do it in a dirty way by adding some codes to the library?
For second approach, i should implement my own function, which simulates the behavior of `get_input_entity()`. This function first checks my own local database and if no match found, it calls `get_entity()` function to retrieve chat info and then stores them in my own local database. Is it correct?

**Comment by Lonami** [comment]
1. Assuming you use the default session storage, you can make SQL queries yourself. This is prone to breaking but I don't expect any change soon.
2. Yes.

**Comment by mehrant95** [comment]
I tried to do it myself but faced some problems. I asked my question in stackoverflow but no helpful answer yet, please take a mintue read [my question](https://stackoverflow.com/questions/52294524/get-username-from-local-session-telethon), I really need your help.
